apps/accounting/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required
from .api import *

from .views_pdf import invoice, ticket, pdf, quotation_pdf

urlpatterns = [
    path('casing/', login_required(CasingList.as_view()), name='casing'),
    path('casing_save/', login_required(casing_save), name='casing_save'),
    path('modal_casing/', login_required(modal_casing), name='modal_casing'),
    path('open_casing/', login_required(open_casing), name='open_casing'),
    path('opening/', login_required(opening), name='opening'),
    path('close_casing/', login_required(close_casing), name='close_casing'),
    path('closing/', login_required(closing), name='closing'),

    path('payable/', login_required(payable), name='payable'),
    path('payment_order/', login_required(payment_order), name='payment_order'),
    path('validate_casing/', login_required(get_validate_casing), name='validate_casing'),
    path('payment_save/', login_required(payment_save), name='payment_save'),
    path('invoice/<int:pk>/', login_required(invoice), name='invoice'),
    path('pdf/<int:pk>/', login_required(pdf), name='pdf'),
    path('quotation_pdf/<int:pk>/', login_required(quotation_pdf), name='quotation_pdf'),
    path('ticket/<int:pk>/', login_required(ticket), name='ticket'),
    path('invoice_list/', login_required(invoice_list), name='invoice_list'),
    path('invoice_issued/', login_required(invoice_issued), name='invoice_issued'),
    path('get_order_type/', login_required(get_order_type), name='get_order_type'),
    path('cancel_recipe/', login_required(cancel_recipe), name='cancel_recipe'),
    path('get_type_invoice/', login_required(get_type_invoice), name='get_type_invoice'),
    path('get_pending_invoices_to_canceled/', login_required(get_pending_invoices_to_canceled), name='get_pending_invoices_to_canceled'),
    path('invoice_sunat/', login_required(invoice_sunat), name='invoice_sunat'),

    path('orders_person_list/', login_required(orders_person_list), name='orders_person_list'),
    path('cash_page/', login_required(cash_page), name='cash_page'),
    path('orders_person/', login_required(orders_person), name='orders_person'),
    path('get_order_by_number/', login_required(get_order_by_number), name='get_order_by_number'),
    path('modal_payment/', login_required(modal_payment), name='modal_payment'),
    path('modal_payment_show/', login_required(modal_payment_show), name='modal_payment_show'),

    path('cash_page/', login_required(cash_page), name='cash_page'),
    path('cash_order/', login_required(cash_order), name='cash_order'),
    path('close_casing/', login_required(close_casing), name='close_casing'),
    path('get_users_by_date/', login_required(get_users_by_date), name='get_users_by_date'),
    path('get_orders_by_user/', login_required(get_orders_by_user), name='get_orders_by_user'),
    path('casing_report/', login_required(casing_report), name='casing_report'),
    path('get_order_list/', login_required(get_order_list), name='get_order_list'),
    path('get_order_detail/', login_required(get_order_detail), name='get_order_detail'),

    path('payments/', login_required(payments), name='payments'),
    path('delete_payment/', login_required(delete_payment), name='delete_payment'),
    path('search_order/', login_required(search_order), name='search_order'),

    # APIS
    path('api/v1/get_ticket_sale/<int:orderNumber>', get_ticket_sale),
    path('api/v1/get_payment_cash/<int:orderNumber>', get_payment_cash),
    path('api/v1/get_close_cash/<str:start_date>/<str:end_date>', get_close_cash),
    path('get_type_change/', login_required(get_type_change), name='get_type_change'),

    # SEND AND CANCEL
    path('invoice_sunat_and_cancel/', login_required(invoice_sunat_and_cancel), name='invoice_sunat_and_cancel'),
    path('send_receipt_sunat/', login_required(send_receipt_sunat), name='send_receipt_sunat'),
    path('send_receipt_cancel/', login_required(send_receipt_cancel), name='send_receipt_cancel'),
    path('invoice_cancel_sunat/', login_required(invoice_cancel_sunat), name='invoice_cancel_sunat'),

    # CREDIT NOTE
    path('modal_credit_note/', login_required(modal_credit_note), name='modal_credit_note'),
    path('save_credit_note/', login_required(save_credit_note), name='save_credit_note'),

    # DEPOSIT REPORT
    path('deposit_report/', login_required(deposit_report), name='deposit_report'),
    path('get_report_deposit/', login_required(get_report_deposit), name='get_report_deposit'),
    path('send_sunat_4_fact/<int:order_id>', send_sunat_4_fact),
]

corporacion_jhunior/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.hrm.views import Home
from apps.user.views import Login, logout_user
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="AVENTURA API",
        default_version='v1',
        description="Documentación ventura",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('docs/', schema_view.with_ui('swagger',
                                                    cache_timeout=0), name='schema-swagger-ui'),
                  path('redocs/', schema_view.with_ui('redoc',
                                                      cache_timeout=0), name='schema-redoc'),
                  path('hrm/', include(('apps.hrm.urls', 'hrm'))),
                  path('user/', include(('apps.user.urls', 'user'))),
                  path('accounting/', include(('apps.accounting.urls', 'accounting'))),
                  path('sales/', include(('apps.sales.urls', 'sales'))),
		  path('finances/', include(('apps.finances.urls', 'finances'))),
                  path('', login_required(Home.as_view()), name='home'),
                  path('accounts/login/', Login.as_view(), name='login'),
                  path('logout/', login_required(logout_user), name='logout'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/accounting/models.py
import decimal
from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from apps.hrm.models import Subsidiary


class Casing(models.Model):
    TYPE_CHOICES = (('C', 'CAJA EFECTIVO'), ('B', 'CUENTA BANCARIA'))
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre', max_length=50)
    description = models.CharField('Descripción', max_length=100, null=True, blank=True)
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    initial = models.DecimalField(max_digits=10, decimal_places=4, default='0')
    is_enabled = models.BooleanField(default=True)
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_status(self):
        status = 'C'
        payment_set = Payments.objects.filter(casing__id=self.id, type__in=['A', 'C'],
                                              subsidiary=self.subsidiary)
        if payment_set:
            status = payment_set.last().type
        return status

    def get_total(self):
        from apps.accounting.views import get_total_money
        total = get_total_money(casing_obj=self)
        t = decimal.Decimal(0.00)
        if total:
            t = total[0].get('total')
        return t

    def total(self):
        payment_set = Payments.objects.filter(subsidiary=self.subsidiary, casing=self)
        t = decimal.Decimal(0.00)
        if payment_set.exists():
            total_i = payment_set.filter(type='I').aggregate(
                r=Coalesce(Sum('amount'), decimal.Decimal(0.00))).get('r')
            total_e = payment_set.filter(type='E').aggregate(
                r=Coalesce(Sum('amount'), decimal.Decimal(0.00))).get('r')
            t = total_i - total_e
        return t

    class Meta:
        verbose_name = 'Cuenta'
        verbose_name_plural = 'Cuentas'


class Payments(models.Model):
    TYPE_CHOICES = (('I', 'INGRESO'), ('E', 'EGRESO'), ('A', 'APERTURA'), ('C', 'CIERRE'))
    PAYMENT_CHOICES = (('E', 'EFECTIVO'), ('D', 'DEPOSITO'), ('C', 'CREDITO'))
    OPERATION_CHOICES = (
        ('O', 'ORDEN'), ('S', 'SALIDA'), ('E', 'ENTRADA'), ('T', 'TRANSFERENCIA'),
        ('R', 'APERTURA/CIERRE'), ('R', 'REEMBOLSO'), ('F', 'FALTANTE'))
    COIN_CHOICES = (('1', 'SOLES'), ('2', 'DOLARES'), ('3', 'EUROS'))
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey('sales.Order', on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    payment = models.CharField('Pago', max_length=1, choices=PAYMENT_CHOICES)
    operation = models.CharField('Operacion', max_length=1, choices=OPERATION_CHOICES)
    code_operation = models.CharField('Codigo de operacion', max_length=50, null=True, blank=True)
    description = models.CharField('Descripcion de la operacion', max_length=250, default='-')
    amount = models.DecimalField('Monto', max_digits=10, decimal_places=4, default=0)
    coin = models.CharField('Moneda', max_length=1, choices=COIN_CHOICES, default='1')
    change_coin = models.DecimalField('Valor de cambio', max_digits=10, decimal_places=4, default=1)
    date_payment = models.DateField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey('user.User', verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, verbose_name='Sede', on_delete=models.SET_NULL, null=True, blank=True)
    casing = models.ForeignKey(Casing, verbose_name='Caja/Cuenta', on_delete=models.SET_NULL, null=True, blank=True)
    group = models.IntegerField('Grupo', default=0)
    credit = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    # def get_debt(self):
    #     total = Payments.objects.filter(order=self.order, status='R', operation='O').aggregate(
    #         r=Coalesce(Sum('amount'), 0)).get('r')
    #     return round(total, 2)

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'


class MoneyChange(models.Model):
    id = models.AutoField(primary_key=True)
    search_date = models.DateField('Fecha de busqueda', null=True, blank=True)
    sunat_date = models.DateField('Fecha de sunat', null=True, blank=True)
    sell = models.DecimalField('Venta', max_digits=10, decimal_places=4, default=0)
    buy = models.DecimalField('Compra', max_digits=10, decimal_places=4, default=0)

    def __str__(self):
        return str(self.id)


class PaymentFees(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey('sales.Order', on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey(Payments, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    amount = models.DecimalField('Importe', max_digits=30, decimal_places=15, default=0)

    def __str__(self):
        return str(self.id)

templates/accounting/casing_list.html
{% extends 'home.html' %}
{% load static %}
{% block title %}
    Caja - Banco
{% endblock title %}

{% block body %}
    <div class="card mt-3">
        <div class="card-header pt-2 pb-2">
            <div class="row d-flex">
                <div class="form-group col-sm-5 col-md-5 m-0 p-1 align-self-center">
                    <h5 class="card-title fw-">Finanzas</h5>
                    <h6 class="card-subtitle text-muted">Cajas - Cuentas Bancarias</h6>
                </div>
                <div class="form-group col-sm-4 col-md-4 m-0 p-1 align-self-center text-center">
                    <input type="text" class="form-control form-control-rounded" id="search"
                           placeholder="Busqueda Cuenta...">
                </div>
                <div class="form-group col-sm-3 col-md-3 m-0 p-1 align-self-center text-center">
                    <button type="button" class="btn btn-light btn-round" onclick="CasingModal('')"><i
                            class="icon-lock"></i> Crear Caja/Cuenta
                    </button>
                </div>
            </div>
        </div>
        <div class="card-body p-2 h-100">
            <div id="detail-items" class="table-responsive-sm text-nowrap">
                <table class="table table-sm table-bordered" style="width: 100%">
                    <thead>
                    <tr class="text-center">
                        <th style="width: 5%">Nº</th>
                        <th style="width: 30%">Caja/Cuenta</th>
                        <th style="width: 30%">Descripción</th>
                        <th style="width: 15%">Inicial</th>
                        <th style="width: 15%">Total</th>
                        <th style="width: 5%">Editar</th>
                    </tr>
                    </thead>
                    <tbody id="casing-list">
                    {% for c in casing_set %}
                        <tr class="text-center">
                            <td class="align-middle p-1">{{ forloop.counter }}</td>
                            <td class="align-middle p-1">{{ c.get_type_display }}</td>
                            <td class="align-middle p-1">{{ c.name }}</td>
                            <td class="align-middle text-right p-1">S/. {{ c.initial|safe }}</td>
                            <td class="align-middle text-right item-total p-1">S/. <b>{{ c.total|safe }}</b></td>
                            <td class="align-middle p-1">
                                <button type="button"
                                        class="btn btn-light"
                                        onclick="CasingModal({{ c.id }})"
                                >
                                    <i class="icon-note"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer p-2">
            <div class="row">
                <div class="col"></div>
                <div class="col"></div>
                <div class="col"></div>
                <div class="col">
                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Total</label>
                        <div class="col-lg-6">
                            <input type="text" value="Mark"
                                   id="total"
                                   name="total"
                                   class="form-control text-right"
                                   placeholder="0.00"
                                   readonly>
                        </div>
                        <label class="col-lg-3 col-form-label form-control-label">Soles</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-casing" data-backdrop="static" data-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true"></div>
    <div class="modal fade" id="modal-open-close" data-backdrop="static" data-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true"></div>
{% endblock body %}

{% block extrajs %}
    <script type="text/javascript">
        let total = parseFloat("0.00")
        $('tbody#casing-list tr td.item-total b').each(function () {
            total = total + parseFloat($(this).text());

        });
        $('#total').val(total.toFixed(2))
        $("#search").keyup(function () {
            _this = this;
            // Show only matching TR, hide rest of them
            $.each($("tbody#casing-list tr"), function () {
                if ($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
                    $(this).hide();
                else
                    $(this).show();
            });
        });

        function CasingModal(pk) {
            $.ajax({
                url: '/accounting/modal_casing/',
                dataType: 'json',
                type: 'GET',
                data: {'pk': pk},
                success: function (response) {
                    if (response.success) {
                        $('#modal-casing').empty().html(response.form).modal('show');
                    }
                },
                fail: function (response) {
                    toastr.error('Error en la petición');
                }
            });
        };

        function OpenCasing(pk) {
            $.ajax({
                url: '/accounting/open_casing/',
                dataType: 'json',
                type: 'GET',
                data: {'pk': pk},
                success: function (response) {
                    if (response.success) {
                        $('#modal-open-close').empty().html(response.grid).modal('show');
                    }
                },
                fail: function (response) {
                    toastr.error('Ocurrio un problema')
                }
            });
        };

        function CloseCasing(pk) {
            $.ajax({
                url: '/accounting/close_casing/',
                dataType: 'json',
                type: 'GET',
                data: {'pk': pk},
                success: function (response) {
                    if (response.success) {
                        $('#modal-open-close').empty().html(response.grid).modal('show');
                    }
                },
                fail: function (response) {
                    toastr.error('Ocurrio un problema')
                }
            });
        };
    </script>
{% endblock extrajs %}

templates/accounting/close.html
{% load static %}
<div class="modal-dialog modal-dialog-centered modal" role="document">
    <form id="formClosing" class="embed-responsive p-0" action="{% url 'accounting:closing' %}"
          method="POST">
        {% csrf_token %}
        <div class="modal-content bg-primary">
            <div class="modal-header">
                <h6 class="modal-title">
                    {{ casing_obj.get_type_display }}: {{ casing_obj.name }}
                    <input type="hidden" class="form-control" id="id-casing-close"
                           name="id-casing-close" value="{{ casing_obj.id }}" required>
                </h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="font-size: 13px;">
                <div class="card m-0">
                    <div class="card-header">
                        <label for="id-date-closing">Fecha de cierre</label>
                        <input type="date" class="form-control" id="id-date-closing"
                               name="date-closing"
                               value="{{ date_now }}" required>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-striped">
                                <tbody>
                                <tr>
                                    <td class="align-middle">TOTAL APERTURA</td>
                                    <td class="amount-aperture-casing align-middle text-right font-weight-bold">{{ total.0.total_aperture|safe }}</td>
                                </tr>
                                <tr>
                                    <td class="align-middle">TOTAL INGRESOS</td>
                                    <td class="amount-entry-casing align-middle text-right font-weight-bold">{{ total.0.total_cash_entry|safe }}</td>
                                </tr>
                                <tr>
                                    <td class="align-middle">TOTAL EGRESOS</td>
                                    <td class="amount-egress-casing align-middle text-right font-weight-bold">{{ total.0.total_cash_egress|safe }}</td>
                                </tr>
                                <tr>
                                    <td class="align-middle">EFECTIVO TOTAL</td>
                                    <td class="amount-cash-casing align-middle text-right font-weight-bold">{{ total.0.total_cash|safe }}</td>
                                </tr>
                                <tr>
                                    <td class="align-middle">TOTAL EN CAJA</td>
                                    <td class="total-cash align-middle text-right font-weight-bold p-1">
                                        <input type="text" id="total-cash" name="total-cash" class="form-control text-right" readonly required value="{{ total.0.total|safe }}"/>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btn-close" class="btn btn-light" data-dismiss="modal">Cerrar</button> &nbsp;
                <button type="submit" id="btn-closing-casing" class="btn btn-light">Cerrar caja
                </button>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('#formClosing').submit(function (event) {
        event.preventDefault();
        if ($('#id-casing-close').val() === '0' || $('#id-casing-close').val() === '') {
            toastr.warning('Especifique la caja que desea cerrar')
            return false;
        }
        if ($('#id-date-closing').val() === '') {
            toastr.warning('Seleccione la fecha de cierre')
            return false;
        }
        let data = new FormData($('#formClosing').get(0));
        $.ajax({
            url: $(this).attr('action'),
            type: $(this).attr('method'),
            data: data,
            cache: false,
            processData: false,
            contentType: false,
            success: function (response) {
                if (response.success) {
                    toastr.success(response.message);
                    setTimeout(() => {
                        location.reload();
                    }, 500);
                    {#if (response.pk) {#}
                    {#    window.open("/accounting/print_ticket_closing_cash/" + response.pk + "/", '_blank');#}
                    {# }#}
                } else {
                    toastr.success(response.message);
                }
            },
            error: function (response) {
                toastr.error('Ocurrio un problema');
            }
        });
    });
</script>

templates/accounting/deposit_report_grid.html
<table id="example1" class="table table-bordered table-striped">
    <thead>
    <tr class="text-center">
        <th>Nº</th>
        <th>Comprobante</th>
        <th>Tipo Comprobante</th>
        <th>Estado</th>
        <th>Fecha</th>
        <th>Pago</th>
        <th>Información Cliente</th>
        <th>Total</th>
{#        <th>Descargar</th>#}
    </tr>
    </thead>
    <tbody id="order_list">
    {% for p in payment_set %}
        <tr class="text-center" order="{{ p.order.id }}">
            <td class="align-middle p-1">{{ p.order.number }}</td>
            <td class="align-middle p-1">
                {% if p.order.bill_number %}
                    {{ p.order.bill_serial }}-{{ p.order.bill_number }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td class="align-middle p-1">{{ p.order.get_doc_display }}</td>
            <td class="align-middle p-1">{{ p.order.get_status_display }}</td>
            <td class="align-middle p-1">{{ p.order.create_at|date:'d-m-Y' }}</td>
            <td class="align-middle p-1">
                {{ p.get_payment_display }}
            </td>
            <td class="text-left text-uppercase align-middle p-1" style="white-space: normal; word-wrap: break-word"><p
                    class="m-0">{{ p.order.person.names }}</p></td>
            <td class="text-right align-middle p-1">{{ p.order.total|safe }}</td>
{#            <td class="align-middle p-1">#}
{#                <button type="button"  onclick="{% if p.order.type == 'T' %}DownloadPDFQuotation({{ p.order.id }}){% else %}DownloadPDF({{ p.order.id }}){% endif %}" class="btn btn-sm btn-warning"><i#}
{#                        class="icon-cloud-download"></i></button>#}
{#            </td>#}
        </tr>
    {% empty %}
        <tr>
            <td colspan="8"><p class="text-warning">No existen resultados</p></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<script type="text/javascript">
    {#    $(document).ready(function() {#}
    {#    $('#table-order').DataTable( {#}
    {#        dom: 'Bfrtip',#}
    {#        buttons: [#}
    {#            'copy', 'csv', 'excel', 'pdf', 'print'#}
    {#        ]#}
    {#    } );#}
    {# } );#}
     $(document).ready(function () {
            $("#example1").DataTable({
                //"ordering": false,
                "order": [[0, 'desc']],
                "aLengthMenu": [1000],
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
</script>

templates/accounting/invoice_grid_list.html
<table class="table table-sm table-bordered">
    <thead>
    <tr class="text-center">
        <th>Nº Comprobante</th>
        <th>Tipo Comprobante</th>
        <th>Orden</th>
        <th>Pago</th>
        <th>Fecha</th>
        <th>Nombres y Apellidos(Razón Social)</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody id="invoice-nubefact">
    {% for o in order_set %}
        <tr class="text-center" order="{{ o.id }}" condition="{{ o.condition }}" status="{{ o.status }}">
            <td class="item-check align-middle p-1">
                <div class="icheck-material-warning m-0">
                    <input type="checkbox" class="value-check" value="" id="{{ o.bill_serial }}-{{ o.bill_number }}" checked>
                    <label class="label-default" for="{{ o.bill_serial }}-{{ o.bill_number }}">{{ o.bill_serial }}-{{ o.bill_number }}</label>
                </div>
{#                <div class="form-check">#}
{#                    <input class="form-check-input" type="checkbox" value=""#}
{#                           id="{{ o.bill_serial }}-{{ o.bill_number }}" checked>#}
{#                    <label class="form-check-label" for="{{ o.bill_serial }}-{{ o.bill_number }}">#}
{#                        {{ o.bill_serial }}-{{ o.bill_number }}#}
{#                    </label>#}
{#                </div>#}
            </td>
            <td class="align-middle p-1">{{ o.get_doc_display }}</td>
            <td class="align-middle p-1">
                {{ o.number }}
            </td>
            <td class="align-middle p-1">
                {{ o.payments_set.first.get_payment_display }}
            </td>
            <td class="align-middle p-1">{{ o.bill_date|date:'d-m-Y' }}</td>
            <td class="text-left text-uppercase align-middle p-1" style="white-space: normal; word-wrap: break-word"><p>{{ o.person.names }}</p></td>
            <td class="text-right align-middle p-1">S/. {{ o.payment_invoice|safe }}</td>
{#            {% if o.status == 'D' and o.doc == '1' %}#}
{#                <td class="text-center align-middle p-1">#}
{#                    <button type="button" class="btn btn-danger btn-sm" pk="{{ o.id }}" onclick="sendNubefactInvoiceAndCancel({{ o.id }})">Enviar y Anular</button>#}
{#                </td>#}
{#            {% endif %}#}
{#            {% if o.status == 'D' and o.doc == '2' %}#}
{#                {% if o.bill_enlace_pdf %}#}
{#                    {% if o.validate_bill_date %}#}
{#                        <td class="text-center align-middle p-1">#}
{#                            <button type="button" class="btn btn-danger btn-sm" pk="{{ o.id }}"#}
{#                                    onclick="sendReceiptCancel({{ o.id }})">Anular#}
{#                            </button>#}
{#                        </td>#}
{#                    {% else %}#}
{#                        <td class="text-center align-middle p-1">#}
{#                            Anulación Pendiente#}
{#                        </td>#}
{#                    {% endif %}#}
{#                {% else %}#}
{#                    <td class="text-center align-middle p-1">#}
{#                        <button type="button" class="btn btn-danger btn-sm" pk="{{ o.id }}"#}
{#                                onclick="sendReceipt({{ o.id }})">Enviar#}
{#                        </button>#}
{#                    </td>#}
{#                {% endif %}#}
{#            {% endif %}#}
        </tr>
    {% empty %}
        <tr>
            <td colspan="7"><p class="text-primary">No existen comprobantes pendientes</p></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/accounting/table_order_detail.html
<div class="tableDetailFixHead">
    <table class="table cab table-hover m-0 table-bordered">
        <thead class="cab">
        <tr class="text-center">
            <th class="cab">Codigo</th>
            <th class="cab">Detalle</th>
            <th class="cab">Cantidad</th>
            <th class="cab">Precio</th>
            <th class="cab">Total</th>
        </tr>
        </thead>
        <tbody>
        {% for d in detail_set %}
            <tr pk="{{ d.id }}" class="text-center">
                <td class="align-middle p-1 cab">{{ d.product.code }}</td>
                <td class="align-middle p-1 cab text-left" style="white-space: normal; word-wrap: break-word">
                    <p class="m-0">{{ d.product.name }}</p></td>
                <td class="align-middle cab p-1">{{ d.quantity|safe }}</td>
                <td class="align-middle cab p-1 text-right">{{ d.price|safe }}</td>
                <td class="align-middle cab p-1 text-right">{{ d.amount|safe }}</td>
            </tr>
        {% empty %}
            <tr>
                <td class="cab" colspan="5"><p class="text-white">No existen resultados</p></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<style>
    .tableDetailFixHead {
        overflow: auto;
        height: 500px;
    }

    .tableDetailFixHead thead th {
        position: sticky;
        top: 0;
        z-index: 1;
    }

    /* Just common table stuff. Really. */
    table.cab {
        border-collapse: collapse;
        width: 100%;
    }

    th.cab, td.cab {
        padding: 8px 16px;
    }

    th.cab {
        background: #7e2f2f;
    }
</style>