apps/sales/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

from .views_excel import ReportProduct, reportkardex, StockMin, purchase_excel, export_product_filter, \
    report_kardex_cont, kardex_excel
from .views_pdf import ticket, guide, logistic, quotation

urlpatterns = [
    path('products/', login_required(ProductList.as_view()), name='products'),
    path('product_save/', login_required(product_save), name='product_save'),
    path('modal_product/', login_required(modal_product), name='modal_product'),
    path('update_product/', login_required(update_product), name='update_product'),
    path('get_search_product/', login_required(get_search_product), name='get_search_product'),

    path('brands/', login_required(BrandList.as_view()), name='brands'),
    path('modal_brand/', login_required(modal_brand), name='modal_brand'),
    path('brand_save/', login_required(brand_save), name='brand_save'),

    path('familys/', login_required(FamilyList.as_view()), name='familys'),
    path('modal_family/', login_required(modal_family), name='modal_family'),
    path('family_save/', login_required(family_save), name='family_save'),

    path('modal_presenting/', login_required(modal_presenting), name='modal_presenting'),
    path('presentation_save/', login_required(presentation_save), name='presentation_save'),
    path('get_presentation/', login_required(get_presentation), name='get_presentation'),
    path('update_presentation/', login_required(update_presentation), name='update_presentation'),
    path('delete_presentation/', login_required(delete_presentation), name='delete_presentation'),

    path('get_store/', login_required(get_store), name='get_store'),
    path('store_save/', login_required(store_save), name='store_save'),

    path('sales/', login_required(SalesList.as_view()), name='sales'),
    path('search_product/', login_required(search_product), name='search_product'),
    path('delete_order_detail/', login_required(delete_order_detail), name='delete_order_detail'),
    path('get_prices/', login_required(get_prices), name='get_prices'),
    path('get_products/', login_required(get_products), name='get_products'),
    path('order_save/', login_required(order_save), name='order_save'),
    path('quotation_save/', login_required(quotation_save), name='quotation_save'),
    path('get_person_by_document/', login_required(get_person_by_document), name='get_person_by_document'),
    path('update_order_detail/', login_required(update_order_detail), name='update_order_detail'),
    path('ticket/<int:pk>/', login_required(ticket), name='ticket'),
    path('quotation/<int:pk>/', login_required(quotation), name='quotation'),
    path('get_order/', login_required(get_order), name='get_order'),
    path('get_search_product_code/', login_required(get_search_product_code), name='get_search_product_code'),

    path('purchase/', login_required(PurchaseList.as_view()), name='purchase'),
    path('get_product_purchase/', login_required(get_product_purchase), name='get_product_purchase'),
    path('get_purchase_by_date/', login_required(get_purchase_by_date), name='get_purchase_by_date'),
    path('get_purchase/', login_required(get_purchase), name='get_purchase'),
    path('purchase_list/', login_required(purchase_list), name='purchase_list'),
    path('valid_unit/', login_required(valid_unit), name='valid_unit'),
    path('purchase_save/', login_required(purchase_save), name='purchase_save'),
    path('pass_purchase/', login_required(pass_purchase), name='pass_purchase'),
    path('cancel_purchase/', login_required(cancel_purchase), name='cancel_purchase'),
    path('get_change/', login_required(get_change), name='get_change'),

    path('modal_kardex/', login_required(modal_kardex), name='modal_kardex'),
    path('get_kardex/', login_required(get_kardex), name='get_kardex'),
    path('get_search_product_other/', login_required(get_search_product_other), name='get_search_product_other'),
    path('get_product_all/', login_required(get_product_all), name='get_product_all'),

    path('sales_list/', login_required(sales_list), name='sales_list'),
    path('get_sales_detail/', login_required(get_sales_detail), name='get_sales_detail'),
    path('modal_guide/', login_required(modal_guide), name='modal_guide'),
    path('modal_kardex_accounting/', login_required(modal_kardex_accounting), name='modal_kardex_accounting'),
    path('guide_save/', login_required(guide_save), name='guide_save'),
    path('guide/<int:pk>/', login_required(guide), name='guide'),
    path('logistic/<int:pk>/', login_required(logistic), name='logistic'),
    path('reportproduct/', ReportProduct.as_view(), name='reportproduct'),
    path('export_product/', login_required(export_product), name='export_product'),
    path('get_kardex_table/', login_required(get_kardex_table), name='get_kardex_table'),
    path('stockmin/', StockMin.as_view(), name='stockmin'),
    path('reportkardex/<str:init>/<str:end>/<int:pk>/', login_required(reportkardex), name='reportkardex'),
    path('report_kardex_cont/<str:init>/<str:end>/<int:pk>/', login_required(report_kardex_cont), name='report_kardex_cont'),
    path('purchase_excel/<str:init>/<str:end>/', login_required(purchase_excel), name='purchase_excel'),
    path('export_product_filter/<str:c1>/<str:c2>/<str:c3>/<str:c4>/<str:array_id>/', login_required(export_product_filter), name='export_product_filter'),

    path('graphic_user/', login_required(graphic_user), name='graphic_user'),
    path('graphic_sales/', login_required(graphic_sales), name='graphic_sales'),
    path('graphic_month/', login_required(graphic_month), name='graphic_month'),

    # Corporate_sale
    path('sales_corporate/', login_required(SalesListCorporate.as_view()), name='sales_corporate'),

    # Cancel Order
    path('cancel_order/', login_required(cancel_order), name='cancel_order'),
    path('get_last_order/', login_required(get_last_order), name='get_last_order'),

    # New Kardex
    path('get_kardex_by_product/', login_required(get_kardex_by_product), name='get_kardex_by_product'),
    path('kardex_excel/<str:month_year>/', login_required(kardex_excel), name='kardex_excel'),

    # TEST FUNCTIONS BACKUP
    path('recalculate_credit_note/', login_required(recalculate_credit_note), name='recalculate_credit_note'),
    path('update_invoice_stock_product/', login_required(update_invoice_stock_product), name='update_invoice_stock_product'),
    path('fill_kardex_invoice/', login_required(fill_kardex_invoice), name='fill_kardex_invoice'),

    # TEST SOCKET
    path('test_socket/', login_required(test_socket), name='test_socket'),

]

corporacion_jhunior/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.hrm.views import Home
from apps.user.views import Login, logout_user
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="AVENTURA API",
        default_version='v1',
        description="Documentación ventura",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('docs/', schema_view.with_ui('swagger',
                                                    cache_timeout=0), name='schema-swagger-ui'),
                  path('redocs/', schema_view.with_ui('redoc',
                                                      cache_timeout=0), name='schema-redoc'),
                  path('hrm/', include(('apps.hrm.urls', 'hrm'))),
                  path('user/', include(('apps.user.urls', 'user'))),
                  path('accounting/', include(('apps.accounting.urls', 'accounting'))),
                  path('sales/', include(('apps.sales.urls', 'sales'))),
		  path('finances/', include(('apps.finances.urls', 'finances'))),
                  path('', login_required(Home.as_view()), name='home'),
                  path('accounts/login/', Login.as_view(), name='login'),
                  path('logout/', login_required(logout_user), name='logout'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/accounting/models.py
import decimal
from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from apps.hrm.models import Subsidiary


class Casing(models.Model):
    TYPE_CHOICES = (('C', 'CAJA EFECTIVO'), ('B', 'CUENTA BANCARIA'))
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre', max_length=50)
    description = models.CharField('Descripción', max_length=100, null=True, blank=True)
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    initial = models.DecimalField(max_digits=10, decimal_places=4, default='0')
    is_enabled = models.BooleanField(default=True)
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_status(self):
        status = 'C'
        payment_set = Payments.objects.filter(casing__id=self.id, type__in=['A', 'C'],
                                              subsidiary=self.subsidiary)
        if payment_set:
            status = payment_set.last().type
        return status

    def get_total(self):
        from apps.accounting.views import get_total_money
        total = get_total_money(casing_obj=self)
        t = decimal.Decimal(0.00)
        if total:
            t = total[0].get('total')
        return t

    def total(self):
        payment_set = Payments.objects.filter(subsidiary=self.subsidiary, casing=self)
        t = decimal.Decimal(0.00)
        if payment_set.exists():
            total_i = payment_set.filter(type='I').aggregate(
                r=Coalesce(Sum('amount'), decimal.Decimal(0.00))).get('r')
            total_e = payment_set.filter(type='E').aggregate(
                r=Coalesce(Sum('amount'), decimal.Decimal(0.00))).get('r')
            t = total_i - total_e
        return t

    class Meta:
        verbose_name = 'Cuenta'
        verbose_name_plural = 'Cuentas'


class Payments(models.Model):
    TYPE_CHOICES = (('I', 'INGRESO'), ('E', 'EGRESO'), ('A', 'APERTURA'), ('C', 'CIERRE'))
    PAYMENT_CHOICES = (('E', 'EFECTIVO'), ('D', 'DEPOSITO'), ('C', 'CREDITO'))
    OPERATION_CHOICES = (
        ('O', 'ORDEN'), ('S', 'SALIDA'), ('E', 'ENTRADA'), ('T', 'TRANSFERENCIA'),
        ('R', 'APERTURA/CIERRE'), ('R', 'REEMBOLSO'), ('F', 'FALTANTE'))
    COIN_CHOICES = (('1', 'SOLES'), ('2', 'DOLARES'), ('3', 'EUROS'))
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey('sales.Order', on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    payment = models.CharField('Pago', max_length=1, choices=PAYMENT_CHOICES)
    operation = models.CharField('Operacion', max_length=1, choices=OPERATION_CHOICES)
    code_operation = models.CharField('Codigo de operacion', max_length=50, null=True, blank=True)
    description = models.CharField('Descripcion de la operacion', max_length=250, default='-')
    amount = models.DecimalField('Monto', max_digits=10, decimal_places=4, default=0)
    coin = models.CharField('Moneda', max_length=1, choices=COIN_CHOICES, default='1')
    change_coin = models.DecimalField('Valor de cambio', max_digits=10, decimal_places=4, default=1)
    date_payment = models.DateField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey('user.User', verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, verbose_name='Sede', on_delete=models.SET_NULL, null=True, blank=True)
    casing = models.ForeignKey(Casing, verbose_name='Caja/Cuenta', on_delete=models.SET_NULL, null=True, blank=True)
    group = models.IntegerField('Grupo', default=0)
    credit = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    # def get_debt(self):
    #     total = Payments.objects.filter(order=self.order, status='R', operation='O').aggregate(
    #         r=Coalesce(Sum('amount'), 0)).get('r')
    #     return round(total, 2)

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'


class MoneyChange(models.Model):
    id = models.AutoField(primary_key=True)
    search_date = models.DateField('Fecha de busqueda', null=True, blank=True)
    sunat_date = models.DateField('Fecha de sunat', null=True, blank=True)
    sell = models.DecimalField('Venta', max_digits=10, decimal_places=4, default=0)
    buy = models.DecimalField('Compra', max_digits=10, decimal_places=4, default=0)

    def __str__(self):
        return str(self.id)


class PaymentFees(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey('sales.Order', on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey(Payments, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    amount = models.DecimalField('Importe', max_digits=30, decimal_places=15, default=0)

    def __str__(self):
        return str(self.id)

apps/hrm/models.py
from django.db import models


class Subsidiary(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    serial = models.CharField(max_length=4, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=45, null=True, blank=True)
    email = models.EmailField(max_length=45, null=True, blank=True)
    ruc = models.CharField('RUC', max_length=11, null=True, blank=True)
    business_name = models.CharField('Razón social', max_length=100, null=True, blank=True)
    representative_name = models.CharField(max_length=100, null=True, blank=True)
    representative_dni = models.CharField(max_length=45, null=True, blank=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    token = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Sucursal'
        verbose_name_plural = 'Sucursales'


class Person(models.Model):
    TYPE_CHOICES = (
        ('C', 'Cliente'), ('P', 'Proveedor'))
    DOCUMENT_CHOICES = (
        ('1', 'DNI'), ('6', 'RUC'))
    id = models.AutoField(primary_key=True)
    type = models.CharField('Cliente - Proveedor', max_length=1, choices=TYPE_CHOICES, default='C', db_index=True)
    document = models.CharField('Tipo Documento', max_length=1, choices=DOCUMENT_CHOICES, default='1')
    number = models.CharField('Numero documento', max_length=15, null=True, blank=True, db_index=True)
    names = models.CharField('Nombres y Apellidos', max_length=200, null=True, blank=True, db_index=True)
    phone = models.CharField(max_length=15, null=True, blank=True, db_index=True)
    email = models.EmailField('Correo', max_length=100, null=True, blank=True)
    address = models.CharField('Direccion', max_length=200, null=True, blank=True, db_index=True)
    license = models.CharField('Licencia de conducir', max_length=15, null=True, blank=True)
    is_enabled = models.BooleanField(default=True, db_index=True)
    discount = models.ForeignKey('hrm.Discount', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.names)

    class Meta:
        verbose_name = 'Cliente - Proveedor'
        verbose_name_plural = 'Clientes - Proveedores'
        indexes = [
            models.Index(fields=['type', 'is_enabled']),
            models.Index(fields=['names', 'number']),
        ]


class Discount(models.Model):
    id = models.AutoField(primary_key=True)
    value = models.DecimalField('Descuento (%)', max_digits=5, decimal_places=2, unique=True, null=True, blank=True)

    def __str__(self):
        return f"{self.value}%"

templates/sales/brand.html
<div class="modal-dialog">
    <form id="formBrand" method="POST" enctype="multipart/form-data" action="{% url 'sales:brand_save' %}">
        {% csrf_token %}
        <div class="modal-content bg-primary">
            <div class="modal-header">
                <h5 class="modal-title text-uppercase" id="staticBackdropLabel">Marca de Producto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="input-1">Nombre Marca</label>
                    <input type="text" class="form-control text-uppercase" id="name" name="name" placeholder="Nombre Marca"
                           value="{{ brand_obj.name }}" required>
                    <input type="hidden" id="brand-pk" name="brand-pk"
                           value="{% if brand_obj %}{{ brand_obj.id }}{% else %}0{% endif %}">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button> &nbsp;
                <button type="submit" class="btn btn-light">{% if brand_obj.id %}Actualizar{% else %}
                    Registrar{% endif %}</button>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('#formBrand').submit(function (event) {
        event.preventDefault();
        let data = new FormData($('#formBrand').get(0));
        $.ajax({
            url: $(this).attr('action'),
            type: $(this).attr('method'),
            data: data,
            cache: false,
            processData: false,
            contentType: false,
            headers: {"X-CSRFToken": '{{ csrf_token }}'},
            success: function (response) {
                if (response.success) {
                    toastr.success(response.message)
                    setTimeout(() => {
                        location.reload();
                    }, 500);
                }
                else{
                    toastr.error(response.message)
                }
            },
            error: function (response) {
                toastr.error('Ocurrio un problema')
            }
        });
    });
</script>

templates/sales/kardex_grid_list.html
<table class="table table-light">
    <thead>
    <tr style="font-size: 8px;" class="text-center">
        <th colspan="3" class="bg-primary">Descripcion</th>
        <th colspan="4" class="bg-signup">Operaciones</th>
        <th colspan="1" class="bg-dark-light">Saldo</th>
    </tr>
    <tr style="font-size: 7px;" class="text-center">
        <th class="align-middle small">Fecha</th>
        <th class="align-middle small">Orden</th>
        <th class="align-middle small">Operación</th>
        <th class="align-middle small">Cantidad</th>
        <th class="align-middle small">Unidades</th>
        <th class="align-middle small">Precio</th>
        <th class="align-middle small">Total</th>
        <th class="align-middle small">Restante</th>
    </tr>
    </thead>
    <tbody>
    {% if detail_set %}
    {% for k in detail_set %}
        {% if forloop.first and k.id == id %}
            <tr class="text-center bg-success-light2" style="font-size: 11px">
                <td class="align-middle">-</td>
                <td class="align-middle">INVENTARIO</td>
                <td class="align-middle">Inicial</td>
                <td class="align-middle">{{ k.previous|safe }} NIU</td>
                <td class="align-middle">{{ k.previous|floatformat:0 }}</td>
                <td class="align-middle text-center">-</td>
                <td class="align-middle text-center">-</td>
                <td class="align-middle text-right">{{ k.previous|safe }}</td>
            </tr>
            {% if k.is_state %}
                <tr class="text-center" style="font-size: 11px">
                    <td class="align-middle">{{ k.order.create_at|date:'d-m-Y' }}</td>
                    <td class="align-middle">{{ k.order.get_type_display }}</td>
                    <td class="align-middle">{{ k.get_operation_display }}</td>
                    <td class="align-middle">{{ k.quantity|safe }} {{ k.unit }}</td>
                    <td class="align-middle">{{ k.quantity_niu }}</td>
                    <td class="align-middle text-right">{{ k.price|safe }}</td>
                    <td class="align-middle text-right">{{ k.amount|safe }}</td>
                    <td class="align-middle text-right">{{ k.quantity_remaining|safe }}</td>
                </tr>
            {% else %}
                <tr class="text-center bg-warning-light2" style="font-size: 11px">
                    <td class="align-middle">{{ k.create_at|date:'d-m-Y' }}</td>
                    {#                    {% if k.order.type == 'V' %}#}
                    {#                        <td class="align-middle">{{ k.order.get_type_display }}</td>#}
                    {#                    {% elif k.order.type == 'C' %}#}
                    <td class="align-middle">{{ k.order.get_type_display }}</td>
                    {#                    {% endif %}#}
                    <td class="align-middle">{{ k.get_operation_display }}</td>
                    <td class="align-middle">{{ k.quantity|safe }} {{ k.unit }}</td>
                    <td class="align-middle">{{ k.quantity_niu }}</td>
                    <td class="align-middle text-right">{{ k.price|safe }}</td>
                    <td class="align-middle text-right">{{ k.amount|safe }}</td>
                    <td class="align-middle text-right">{{ k.quantity_remaining|safe }}</td>
                </tr>
            {% endif %}
        {% else %}
            {% if k.is_state %}
                <tr class="text-center" style="font-size: 11px">
                    <td class="align-middle">{{ k.order.create_at|date:'d-m-Y' }}</td>
                    <td class="align-middle">{{ k.order.get_type_display }}</td>
                    <td class="align-middle">{{ k.get_operation_display }}</td>
                    <td class="align-middle">{{ k.quantity|safe }} {{ k.unit }}</td>
                    <td class="align-middle">{{ k.quantity_niu }}</td>
                    <td class="align-middle text-right">{{ k.price|safe }}</td>
                    <td class="align-middle text-right">{{ k.amount|safe }}</td>
                    <td class="align-middle text-right">{{ k.quantity_remaining|safe }}</td>
                </tr>
            {% else %}
                <tr class="text-center bg-warning-light2" style="font-size: 11px">
                    <td class="align-middle">{{ k.create_at|date:'d-m-Y' }}</td>
                    <td class="align-middle">{{ k.order.get_type_display }}</td>
                    <td class="align-middle">{{ k.get_operation_display }}</td>
                    <td class="align-middle">{{ k.quantity|safe }} {{ k.unit }}</td>
                    <td class="align-middle">{{ k.quantity_niu }}</td>
                    <td class="align-middle text-right">{{ k.price|safe }}</td>
                    <td class="align-middle text-right">{{ k.amount|safe }}</td>
                    <td class="align-middle text-right">{{ k.quantity_remaining|safe }}</td>
                </tr>
            {% endif %}
        {% endif %}
    {% endfor %}
    {% else %}
        <tr class="text-center bg-success-light2" style="font-size: 11px">
          <td class="align-middle">-</td>
                <td class="align-middle">INVENTARIO</td>
                <td class="align-middle">Inicial</td>
                <td class="align-middle">{{ product_obj.stock|safe }} NIU</td>
                <td class="align-middle">{{ product_obj.stock|floatformat:0 }}</td>
                <td class="align-middle text-center">-</td>
                <td class="align-middle text-center">-</td>
                <td class="align-middle text-right">{{ product_obj.stock|safe }}</td>
        </tr>
    {% endif %}
    </tbody>
</table>

templates/sales/product_grid_list.html
<table id="table-product" class="table table-striped small" style="width: 100%">
    <thead>
    <tr class="text-center">
        <th style="width: 1%"><i class='icon-check text-white'></i></th>
        <th style="width: 3%">Nº</th>
        <th style="width: 20%">Descripción</th>
        <th style="width: 7%">Marca</th>
        <th style="width: 7%">Familia</th>
        <th style="width: 8%">Tipo</th>
        <th style="width: 7%">Estado</th>
        <th style="width: 10%">Medidas</th>
        <th style="width: 12%">Almacen</th>
        <th style="width: 12%">Relacion</th>
        <th style="width: 13%">Acción</th>
    </tr>
    </thead>
    <tbody class="product_detail">
    {% for p in product_set %}
        <tr pk="{{ p.id }}" i="{{ forloop.counter }}" class="{% if p.stock <= p.minimum %} bg-danger{% endif %}">
            <td class="align-middle text-center item-check" >
                <input type="checkbox" class="requirement align-middle" pk="{{ p.id }}" style=" transform: scale(1.2);">
            </td>
            <td class="align-middle text-center item-number p-1">{{ forloop.counter }}</td>
            <td class="align-middle item-name p-1" code="{{ p.code }}" name="{{ p.name }}">
                <strong>CODIGO: {{ p.code }}<br>{{ p.name }}<br>{{ p.description }}
                </strong>
            </td>
            <td class="align-middle text-center item-brand p-1">{{ p.brand.name }}</td>
            <td class="align-middle text-center item-family p-1">{{ p.family.name }}</td>
            <td class="align-middle text-center item-type p-1">
                    {{ p.get_type_display }}
            </td>
            <td class="align-middle text-center item-state p-1" state="{{ p.is_state }}">
                {% if p.is_state %}
                    <i class='icon-check text-white'></i>
                {% else %}
                    <i class='icon-close text-white'></i>
                {% endif %}
            </td>
            <td class="align-middle item-measure p-1" a="{{ p.width }}" l="{{ p.length }}" h="{{ p.height }}">
                <strong>ANCHO: {{ p.width }}<br>LARGO: {{ p.length }}<br>ALTO: {{ p.height }}</strong>
            </td>
            <td class="align-middle item-store p-1" store="{{ p.store }}" stock="{{ p.stock|safe }}" minimum="{{ p.minimum|safe }}">
                <strong>ALMACÉN: {{ p.store }}<br>STOCK : {{ p.stock|safe }}<br>MINIMO: {{ p.minimum|safe }}</strong>
            </td>
            <td class="align-middle item-relation p-1">
              <input type="text" maxlength="50" class="form-control text-uppercase" value="{{ p.relation }}">
            </td>
            <td class="align-middle text-center item-action p-1">
                <button type="button"
                        class="btn btn-light"
                        onclick="showModal({{ p.id }})"
                >
                    <i class="icon-note"></i>
                </button>
                <button type="button" class="btn btn-light"
                        onclick="showPrice({{ p.id }})">
                    <i class="icon-paypal"></i>
                </button>
{#                <button type="button" class="btn btn-light"#}
{#                        onclick="showKardex({{ p.id }})">#}
{#                    <i class="icon-home"></i>#}
{#                </button>#}
                <button type="button" class="btn btn-light button-kardex" pk="{{ p.id }}"
                        onclick="showKardexAccounting({{ p.id }})"
                >
                    <i class="icon-home"></i>
                </button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/sales/test_socket.html
{% extends 'home.html' %}
{% load static %}
{% block title %}
    test
{% endblock title %}

{% block body %}

    TESTEADOR OFICIAL BY JHON A.K.A. EL TIBU
    <div class="card">
        <div class="card-header pr-3 border-0 pb-2">
            <div class="row">
                <div class="col-md-2">
                    <input type="text" class="form-control form-control-rounded"
                           id="search-code"
                           name="search-code"
                           placeholder="NUMBER"/>
                </div>
                <div class="col-md-2">
                    <button type="button" id="btn-new-window" class="btn btn-light w-100">
                        <i class="fa fa-file" aria-hidden="true"></i> SOCKETE
                    </button>
                </div>
            </div>
        </div>
    </div>


{% endblock body %}

{% block extrajs %}
    <script type="text/javascript">
        const btnNewWindow = document.getElementById('btn-new-window');
        const searchCodeInput = document.getElementById('search-code');

        btnNewWindow.addEventListener('click', function () {
            const inputValue = searchCodeInput.value;

            // Abrir una nueva conexión WebSocket en cada clic
            const socket = new WebSocket("ws://localhost:5000/ws");

            socket.onopen = () => {
                console.log("✅ Conectado al servidor WebSocket");
                socket.send(inputValue); // Enviar el texto del input
                console.log("📤 Mensaje enviado:", inputValue);

                // Cerrar la conexión inmediatamente después del envío
                socket.close();
            };

            socket.onerror = (error) => {
                console.error("❌ Error en el WebSocket:", error);
            };

            socket.onclose = (event) => {
                console.log("🔌 Conexión cerrada:", event);
            };
        });


    </script>
{% endblock extrajs %}