corporacion_jhunior/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.hrm.views import Home
from apps.user.views import Login, logout_user
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="AVENTURA API",
        default_version='v1',
        description="Documentación ventura",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('docs/', schema_view.with_ui('swagger',
                                                    cache_timeout=0), name='schema-swagger-ui'),
                  path('redocs/', schema_view.with_ui('redoc',
                                                      cache_timeout=0), name='schema-redoc'),
                  path('hrm/', include(('apps.hrm.urls', 'hrm'))),
                  path('user/', include(('apps.user.urls', 'user'))),
                  path('accounting/', include(('apps.accounting.urls', 'accounting'))),
                  path('sales/', include(('apps.sales.urls', 'sales'))),
		  path('finances/', include(('apps.finances.urls', 'finances'))),
                  path('', login_required(Home.as_view()), name='home'),
                  path('accounts/login/', Login.as_view(), name='login'),
                  path('logout/', login_required(logout_user), name='logout'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/sales/models.py
import decimal
from django.db import models
from django.db.models import Sum, F, DecimalField
from django.db.models.functions import Coalesce
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust
from apps.accounting.models import Payments
from apps.hrm.models import Person, Subsidiary


class Product(models.Model):
    TYPE_CHOICES = (('A', 'ARMADO'), ('P', 'PIEZA'))
    id = models.AutoField(primary_key=True)
    code = models.CharField('Codigo', max_length=20, null=True, blank=True)
    name = models.CharField('Nombre', max_length=300, null=True, blank=True)
    description = models.CharField('Descripción', max_length=300, null=True, blank=True)
    family = models.ForeignKey('Family', on_delete=models.CASCADE, null=True, blank=True)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField('Tipo Producto', max_length=1, choices=TYPE_CHOICES, default='P')

    # photo = models.ImageField(upload_to='product/',
    #                           default='product/product0.jpg', blank=True)
    # photo_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(
    #     100, 100)], source='photo', format='JPEG', options={'quality': 90})
    is_state = models.BooleanField('Estado', default=True)
    width = models.CharField('Ancho', max_length=100, null=True, blank=True)
    length = models.CharField('Largo', max_length=100, null=True, blank=True)
    height = models.CharField('Alto', max_length=100, null=True, blank=True)
    store = models.CharField('Alamacen', max_length=100, null=True, blank=True)
    minimum = models.DecimalField('Stock Minimo', max_digits=30, decimal_places=4, default=0)
    stock = models.DecimalField('Stock Producto', max_digits=30, decimal_places=4, default=0)
    relation = models.CharField('Codigo Relacional', max_length=100, null=True, blank=True)
    is_discount = models.BooleanField('Descuento', default=False)
    invoice_stock = models.DecimalField('Invoice Stock', max_digits=30, decimal_places=4, default=0)

    def __str__(self):
        return str(self.name)

    def valued_total(self):
        if self.stock:
            presenting_set = Presentation.objects.filter(product=self, unit='NIU', quantity=decimal.Decimal(1.0000),
                                                         quantity_niu=1)
            if presenting_set.exists():
                price = presenting_set.first().price
                return round(self.stock * decimal.Decimal(price), 4)
            else:
                return decimal.Decimal(0.0000)
        else:
            return decimal.Decimal(0.0000)

    def price_unit(self):
        if self.presentation_set:
            presenting_set = Presentation.objects.filter(product=self, unit='NIU', quantity=decimal.Decimal(1.0000),
                                                         quantity_niu=1)
            if presenting_set.exists():
                price = presenting_set.first().price
                return round(price, 4)
            else:
                return decimal.Decimal(0.0000)
        else:
            return decimal.Decimal(0.0000)

    def measure(self):
        if self.width:
            width = str(self.width.strip())
        else:
            width = ''
        if self.length:
            self.length = (self.length).strip()
            if self.length != 'NULL' and self.length != 'NONE' and self.length != '' and len(self.length) > 0:
                length = ' x ' + str(self.length.strip())
            else:
                length = ''
        else:
            length = ''
        if self.height:
            self.height = (self.height).strip()
            if self.height != 'NULL' and self.height != 'NONE' and self.height != '' and len(self.height) > 0:
                height = ' x ' + str(self.height.strip())
            else:
                height = ''
        else:
            height = ''

        return str(width) + str(length) + str(height)

    def complete_name(self):
        return self.name + ' ' + self.measure()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'


class Presentation(models.Model):
    UNIT_CHOICES = (('NIU', 'UNIDAD'), ('KGM', 'KILO'), ('BG', 'BOLSA'), ('BX', 'CAJA'))
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    unit = models.CharField('Unidad', max_length=3, choices=UNIT_CHOICES, default='NIU')
    price = models.DecimalField('Precio de Venta', max_digits=10, decimal_places=4, default=0)
    quantity = models.DecimalField('Cantidad Minima', max_digits=10, decimal_places=4, default=0)
    quantity_niu = models.IntegerField('Cantidad Unidades', default=1)
    is_elderly = models.BooleanField('Precio Mayor', default=False)
    is_corporate = models.BooleanField('Venta Corporativa', default=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Presentación'
        verbose_name_plural = 'Presentaciones'


# class ProductDetail(models.Model):
#     id = models.AutoField(primary_key=True)
#     input = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='input')
#     output = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='output')
#
#     def __str__(self):
#         return str(self.output.name)
#
#     class Meta:
#         verbose_name = 'Detalle Producto'
#         verbose_name_plural = 'Detalle Productos'


class Family(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre Familia', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Familia'
        verbose_name_plural = 'Familias'


class Brand(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre Marca', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'


# class Unit(models.Model):
#     id = models.AutoField(primary_key=True)
#     name = models.CharField('Abreviatura', max_length=5, unique=True)
#     description = models.CharField('Descripción', max_length=100, unique=True)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = 'Unidad'
#         verbose_name_plural = 'Unidades'


class Order(models.Model):
    TYPE_CHOICES = (('T', 'COTIZACIÓN'), ('V', 'VENTA'), ('C', 'COMPRA'))
    COIN_CHOICES = (('1', 'SOLES'), ('2', 'DOLARES'))
    MOTIVE_CHOICES = (('01', 'VENTA'), ('14', 'VENTA SUJETA A CONFIRMACION DEL COMPRADOR'), ('02', 'COMPRA'),
                      ('04', 'TRASLADO ENTRE ESTABLECIMIENTOS DE LA MISMA EMPRESA'),
                      ('18', 'TRASLADO EMISOR ITINERANTE CP'),
                      ('08', 'IMPORTACION'), ('09', 'EXPORTACION'), ('13', 'OTROS'), ('06', 'DEVOLUCION'),)
    DOC_CHOICES = (('0', 'ORDEN'), ('1', 'FACTURA ELECTRÓNICA'), ('2', 'BOLETA ELECTRÓNICA'), ('3', 'NOTA DE CREDITO'),
                   ('4', 'NOTA DE DEBITO'), ('5', 'GUIA DE REMISION'))
    ADD_CHOICES = (('N', 'NINGUNA'), ('G', 'GUIA DE REMISIÓN'))
    MODALITY_TRANSPORT_CHOICES = (('1', 'PUBLICO'), ('2', 'PRIVADO'))
    STATUS_CHOICES = (
        ('P', 'PENDIENTE'), ('R', 'REALIZADA'), ('E', 'EMITIDO'), ('A', 'ANULADA'), ('N', 'NOTA DE CREDITO'),
        ('G', 'GUIA DE REMISION'))
    CONDITION_CHOICES = (('R', 'REALIZADO'), ('PA', 'PENDIENTE ANULACION'), ('A', 'ANULADA'))
    id = models.AutoField(primary_key=True)
    type = models.CharField('TIPO', max_length=1, choices=TYPE_CHOICES, default='T')
    doc = models.CharField('Documento', max_length=1, choices=DOC_CHOICES, default='0')
    add = models.CharField('Adicionales', max_length=1, choices=ADD_CHOICES, default='N')
    number = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    correlative = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    status = models.CharField('ESTADO', max_length=1, choices=STATUS_CHOICES, default='P')
    total = models.DecimalField('TOTAL', max_digits=30, decimal_places=6, default=0)
    total_discount = models.DecimalField('DESCUENTO', max_digits=30, decimal_places=4, default=0)
    coin = models.CharField('TIPO', max_length=1, choices=COIN_CHOICES, default='1')
    change = models.DecimalField('CAMBIO DE MONEDA', max_digits=30, decimal_places=4, default=1)
    create_at = models.DateField(null=True, blank=True)
    update_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True, blank=True)
    person = models.ForeignKey(Person, verbose_name='CLIENTE/PROVEEDOR',
                               on_delete=models.SET_NULL, null=True, blank=True)
    quotation = models.IntegerField(verbose_name='COTIZACION', null=True, blank=True)
    is_igv = models.BooleanField('IGV', default=True)
    date_document = models.DateField(null=True, blank=True)
    invoice_number = models.CharField('Numero Factura', max_length=50, null=True, blank=True)
    invoice_date = models.DateField("Fecha Ingreso", null=True, blank=True)
    license_plate = models.CharField('Placa', max_length=50, null=True, blank=True)
    paid = models.DecimalField('PAGADO', max_digits=30, decimal_places=4, default=0)
    bill_serial = models.CharField(max_length=50, null=True, blank=True, default='-')
    bill_type = models.CharField('TIPO', max_length=2, null=True, blank=True)
    bill_number = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    bill_status = models.CharField('Sunat Status', max_length=5, null=True, blank=True)
    bill_description = models.CharField('Sunat descripcion', max_length=500, null=True, blank=True)
    bill_enlace_pdf = models.CharField('Sunat Enlace Pdf', max_length=500, null=True, blank=True)

templates/graphic/graphic_sales_payment.html
{% extends 'index.html' %}

{% block title %}
    System | Grafico
{% endblock title %}

{% block body %}
    <div class="card-header p-0 m-0  small border-bottom-primary roboto-condensed-regular">
        <div class="row col-sm-12 col-md-12 col-lg-12">
            <div class="col-sm-2 col-md-2 col-lg-2  text-center align-self-center mt-1 mb-1">
                <input type="week" id="id-week" class="form-control form-control-sm" value="">
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2 text-center align-self-center mt-1 mb-1">
                <button type="button" onclick="ShowGraphic('graphic_sales_payment_view')"
                        class="btn btn-sm btn-outline-success" style="font-size: 14px;"><i class="fas fa-chart-bar"></i>
                    Mostrar grafica
                </button>
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3 text-center align-self-center mt-1 mb-1"></div>
            <div class="col-sm-5 col-md-5 col-lg-5 text-center align-self-center mt-1 mb-1"></div>
        </div>
    </div>
    <!-- Content -->
    <div class="container-fluid  p-0 m-0 roboto-condensed-regular">
        <div class="col-sm-12 col-md-12 col-lg-12  p-0 m-0" id="id-table-graphic" style="height: 100%; overflow-y: scroll;"></div>
    </div>
{% endblock body %}

{% block extrajs %}
    <script type="text/javascript">
        function ShowGraphic(route) {
            if ($('#id-week').val() === '') {
                toastr.warning('Seleccione una semana', 'Grafica');
                return false;
            }
            $('#id-table-graphic').empty();
            $.ajax({
                url: '/purchase/' + route + '/',
                dataType: 'json',
                type: 'GET',
                data: {'week': $('#id-week').val()},
                success: function (response) {
                   $('#id-table-graphic').html(response['grid']);
                },
                fail: function (response) {
                    toastr.error('Problemas al mostrar la grafica', '¡Mensaje!');
                }
            });
        };
    </script>
{% endblock extrajs %}

templates/graphic/graphic_sales_payment_grid.html
<div class="card p-0  m-0 mt-1" style="border-color: #2681d0">
    <div class="card-header text-center p-1" style="background: #2681d0">
        <h6 class="card-title text-white m-0 p-0 roboto-condensed-regular">GRAFICO DE PAGOS</h6>
    </div>
    <div class="card-body p-0 m-0">
        <figure class="highcharts-figure col-sm-12 col-md-12 col-lg-12 response">
            <div class="col-sm-12 col-md-12 col-lg-12 p-0 m-0" id="container"></div>
        </figure>
    </div>
</div>
<script type="text/javascript">
    Highcharts.chart('container', {
        title: {
            text: 'Modalidad de Pagos'
        },
        xAxis: {
            categories: ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']
        },
        labels: {
            items: [{
                html: 'Total Semana',
                style: {
                    left: '95px',
                    top: '-30px',
                    color: ( // theme
                        Highcharts.defaultOptions.title.style &&
                        Highcharts.defaultOptions.title.style.color
                    ) || 'black'
                }
            }]
        },
        series: [{
            type: 'column',
            name: 'Efectivo',
            data: {{ cash_payment|safe }}
        }, {
            type: 'column',
            name: 'Deposito',
            data: {{ deposit_payment|safe }}/**[2, 3, 5, 7, 6, 4, 6]**/
        }, {
            type: 'column',
            name: 'Credito',
            data: {{ credit_payment|safe }}
        }, {
            type: 'spline',
            name: 'Efectivo y Deposito',
            data: {{ cash_deposit_payment|safe }},
            marker: {
                lineWidth: 2,
                lineColor: Highcharts.getOptions().colors[3],
                fillColor: 'white'
            }
        }, {
            type: 'pie',
            name: 'Total S/.',
            data: [{
                name: 'Efectivo',
                y: {{ total_cash_week|safe }},
                color: Highcharts.getOptions().colors[0] //color
            }, {
                name: 'Deposito',
                y: {{ total_deposit_week|safe }},
                color: Highcharts.getOptions().colors[1] //color
            }, {
                name: 'Credito',
                y: {{ total_credit_week|safe }},
                color: Highcharts.getOptions().colors[2] //color
            }],
            center: [110, 50],
            size: 100,
            showInLegend: false,
            dataLabels: {
                enabled: true
            }
        }]
    });
</script>

templates/graphic/graphic_sales_product.html
{% extends 'index.html' %}

{% block title %}
    Grafico|Producto
{% endblock title %}

{% block body %}
    <div class="card">
        <div class="card-header p-0 m-0 small roboto-condensed-regular">
            <div class="row col-sm-12 col-md-12 col-lg-12">
                <div class="col-sm-8 col-md-8 col-lg-8 align-self-center mt-1 mb-1 pl-2">
                    <select id="id-product" name="id-product[]" class="form-control"
                            multiple="multiple">
                        <option value="0">Producto</option>
                        {% for p in product_set %}
                            <option value="{{ p.id }}">{{ p.names }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2  text-center align-self-center mt-1 mb-1">
                    <input type="week" id="id-week" class="form-control form-control-sm" value="">
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2 text-center align-self-center mt-1 mb-1">
                    <button type="button" onclick="ShowGraphic('graphic_sales_product_grid')"
                            class="btn btn-sm btn-outline-primary" style="font-size: 14px;"><i
                            class="fas fa-chart-bar"></i>
                        Mostrar grafica
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- Content -->
    <div class="container-fluid  p-0 m-0 roboto-condensed-regular">
        <div class="col-sm-12 col-md-12 col-lg-12  p-0 m-0" id="id-table-graphic"
             style="height: 100%; overflow-y: scroll;"></div>
    </div>
{% endblock body %}

{% block extrajs %}
    <script type="text/javascript">
        $('#id-product').select2();

        function ShowGraphic(route) {
            if ($('#id-week').val() === '' || $('#id-week').val() === 0) {
                toastr.warning('Seleccione la semana', 'Grafica');
                return false;
            }
            if($('#id-product').text() === ""){
                 toastr.warning('Seleccione los productos', 'Grafica');
                return false;
            }
            $('#id-table-graphic').empty();
            $.ajax({
                url: '/purchase/' + route + '/',
                dataType: 'json',
                type: 'GET',
                data: {'week': $('#id-week').val(), 'products': JSON.stringify($('#id-product').val())},
                success: function (response) {
                    if(response.success){
                        $('#id-table-graphic').html(response['grid']);
                    }
                    else{
                        toastr.warning(response.message);
                    }
                },
                fail: function (response) {
                    toastr.error('Problemas al mostrar la grafica', '¡Mensaje!');
                }
            });
        };
    </script>
{% endblock extrajs %}

templates/graphic/graphic_sales_product_grid.html
<div class="card p-0  m-0 mt-1" style="border-color: #2681d0">
    <div class="card-header text-center p-1" style="background: #2681d0">
        <h6 class="card-title text-white m-0 p-0 roboto-condensed-regular">GRAFICO DE PRODUCTOS VENDIDOS</h6>
    </div>
    <div class="card-body p-0 m-0">
        <figure class="highcharts-figure col-sm-12 col-md-12 col-lg-12 response">
            <div class="col-sm-12 col-md-12 col-lg-12 p-0 m-0" id="container"></div>
        </figure>
    </div>
</div>
<script type="text/javascript">
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'PRODUCTOS'
        },
        subtitle: {
            text: 'Venta de productos por dia'
        },
        xAxis: {
            categories: [
                'Lunes',
                'Martes',
                'Miercoles',
                'Jueves',
                'Viernes',
                'Sabado',
                'Domingo'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Cantidad vendida (Unidades)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} Unidades</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [
            {% for p in product_grid_list %}
                {
                    name: "{{ p.name }}",
                    data: {{ p.data }}
                },
            {% endfor %}
        ]
    });
</script>

templates/graphic/graphic_sales_purchase_grid.html
<div class="card p-0  m-0 mt-1" style="border-color: #2681d0">
    <div class="card-header text-center p-1" style="background: #2681d0">
        <h6 class="card-title text-white m-0 p-0 roboto-condensed-regular">GRAFICO ESTADISTICO</h6>
    </div>
    <div class="card-body p-0 m-0">
        <figure class="highcharts-figure col-sm-12 col-md-12 col-lg-12 response">
            <div class="col-sm-12 col-md-12 col-lg-12 p-0 m-0" id="container"></div>
        </figure>
    </div>
</div>
<script type="text/javascript">

    Highcharts.chart('container', {
        chart: {
            zoomType: 'xy',
        },
        title: {
            text: 'COMPRAS - VENTAS'
        },
        subtitle: {
            text: 'SEDE: {{ subsidiary_obj.name }}'
        },
        xAxis: [{
            categories: ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
                'Domingo'],
            crosshair: true
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: 'S/. {value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            title: {
                text: 'Compras',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }
        }, { // Secondary yAxis
            title: {
                text: 'Ventas',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            labels: {
                format: 'S/. {value}',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            opposite: true
        }],
        tooltip: {
            shared: true
        },
        legend: {
            layout: 'vertical',
            align: 'left',
            x: 120,
            verticalAlign: 'top',
            y: 100,
            floating: true,
            backgroundColor:
                Highcharts.defaultOptions.legend.backgroundColor || // theme
                'rgba(255,255,255,0.25)'
        },
        series: [{
            name: 'Ventas',
            type: 'column',
            yAxis: 1,
            data: {{ sales|safe }},
            tooltip: {
                valueSuffix: ' Soles'
            }

        }, {
            name: 'Compras',
            type: 'spline',
            data: {{ purchase|safe }},
            tooltip: {
                valueSuffix: ' Soles'
            }
        }]
    });
</script>