apps/finances/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

from .views_pdf import guide_return

urlpatterns = [

    path('orders_supplier_list/', login_required(orders_supplier_list), name='orders_supplier_list'),
    path('get_orders_purchased/', login_required(get_orders_purchased), name='get_orders_purchased'),
    path('get_order_purchased_by_id/', login_required(get_order_purchased_by_id), name='get_order_purchased_by_id'),
    path('credit_note_supplier_save/', login_required(credit_note_supplier_save), name='credit_note_supplier_save'),
    path('credit_note_supplier_review/', login_required(credit_note_supplier_review), name='credit_note_supplier_review'),
    path('purchase_review/', login_required(purchase_review), name='purchase_review'),
    path('annul_credit_note_by_id/', login_required(annul_credit_note_by_id), name='annul_credit_note_by_id'),

    path('modal_guide/', login_required(modal_guide), name='modal_guide'),
    path('guide_return_save/', login_required(guide_return_save), name='guide_return_save'),
    path('guide_return/<int:pk>/', login_required(guide_return), name='guide_return'),
]

corporacion_jhunior/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.hrm.views import Home
from apps.user.views import Login, logout_user
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="AVENTURA API",
        default_version='v1',
        description="Documentación ventura",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('docs/', schema_view.with_ui('swagger',
                                                    cache_timeout=0), name='schema-swagger-ui'),
                  path('redocs/', schema_view.with_ui('redoc',
                                                      cache_timeout=0), name='schema-redoc'),
                  path('hrm/', include(('apps.hrm.urls', 'hrm'))),
                  path('user/', include(('apps.user.urls', 'user'))),
                  path('accounting/', include(('apps.accounting.urls', 'accounting'))),
                  path('sales/', include(('apps.sales.urls', 'sales'))),
		  path('finances/', include(('apps.finances.urls', 'finances'))),
                  path('', login_required(Home.as_view()), name='home'),
                  path('accounts/login/', Login.as_view(), name='login'),
                  path('logout/', login_required(logout_user), name='logout'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/finances/models.py
from django.db import models

# Create your models here.

apps/sales/models.py
import decimal
from django.db import models
from django.db.models import Sum, F, DecimalField
from django.db.models.functions import Coalesce
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust
from apps.accounting.models import Payments
from apps.hrm.models import Person, Subsidiary


class Product(models.Model):
    TYPE_CHOICES = (('A', 'ARMADO'), ('P', 'PIEZA'))
    id = models.AutoField(primary_key=True)
    code = models.CharField('Codigo', max_length=20, null=True, blank=True)
    name = models.CharField('Nombre', max_length=300, null=True, blank=True)
    description = models.CharField('Descripción', max_length=300, null=True, blank=True)
    family = models.ForeignKey('Family', on_delete=models.CASCADE, null=True, blank=True)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField('Tipo Producto', max_length=1, choices=TYPE_CHOICES, default='P')

    # photo = models.ImageField(upload_to='product/',
    #                           default='product/product0.jpg', blank=True)
    # photo_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(
    #     100, 100)], source='photo', format='JPEG', options={'quality': 90})
    is_state = models.BooleanField('Estado', default=True)
    width = models.CharField('Ancho', max_length=100, null=True, blank=True)
    length = models.CharField('Largo', max_length=100, null=True, blank=True)
    height = models.CharField('Alto', max_length=100, null=True, blank=True)
    store = models.CharField('Alamacen', max_length=100, null=True, blank=True)
    minimum = models.DecimalField('Stock Minimo', max_digits=30, decimal_places=4, default=0)
    stock = models.DecimalField('Stock Producto', max_digits=30, decimal_places=4, default=0)
    relation = models.CharField('Codigo Relacional', max_length=100, null=True, blank=True)
    is_discount = models.BooleanField('Descuento', default=False)
    invoice_stock = models.DecimalField('Invoice Stock', max_digits=30, decimal_places=4, default=0)

    def __str__(self):
        return str(self.name)

    def valued_total(self):
        if self.stock:
            presenting_set = Presentation.objects.filter(product=self, unit='NIU', quantity=decimal.Decimal(1.0000),
                                                         quantity_niu=1)
            if presenting_set.exists():
                price = presenting_set.first().price
                return round(self.stock * decimal.Decimal(price), 4)
            else:
                return decimal.Decimal(0.0000)
        else:
            return decimal.Decimal(0.0000)

    def price_unit(self):
        if self.presentation_set:
            presenting_set = Presentation.objects.filter(product=self, unit='NIU', quantity=decimal.Decimal(1.0000),
                                                         quantity_niu=1)
            if presenting_set.exists():
                price = presenting_set.first().price
                return round(price, 4)
            else:
                return decimal.Decimal(0.0000)
        else:
            return decimal.Decimal(0.0000)

    def measure(self):
        if self.width:
            width = str(self.width.strip())
        else:
            width = ''
        if self.length:
            self.length = (self.length).strip()
            if self.length != 'NULL' and self.length != 'NONE' and self.length != '' and len(self.length) > 0:
                length = ' x ' + str(self.length.strip())
            else:
                length = ''
        else:
            length = ''
        if self.height:
            self.height = (self.height).strip()
            if self.height != 'NULL' and self.height != 'NONE' and self.height != '' and len(self.height) > 0:
                height = ' x ' + str(self.height.strip())
            else:
                height = ''
        else:
            height = ''

        return str(width) + str(length) + str(height)

    def complete_name(self):
        return self.name + ' ' + self.measure()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'


class Presentation(models.Model):
    UNIT_CHOICES = (('NIU', 'UNIDAD'), ('KGM', 'KILO'), ('BG', 'BOLSA'), ('BX', 'CAJA'))
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    unit = models.CharField('Unidad', max_length=3, choices=UNIT_CHOICES, default='NIU')
    price = models.DecimalField('Precio de Venta', max_digits=10, decimal_places=4, default=0)
    quantity = models.DecimalField('Cantidad Minima', max_digits=10, decimal_places=4, default=0)
    quantity_niu = models.IntegerField('Cantidad Unidades', default=1)
    is_elderly = models.BooleanField('Precio Mayor', default=False)
    is_corporate = models.BooleanField('Venta Corporativa', default=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Presentación'
        verbose_name_plural = 'Presentaciones'


# class ProductDetail(models.Model):
#     id = models.AutoField(primary_key=True)
#     input = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='input')
#     output = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='output')
#
#     def __str__(self):
#         return str(self.output.name)
#
#     class Meta:
#         verbose_name = 'Detalle Producto'
#         verbose_name_plural = 'Detalle Productos'


class Family(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre Familia', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Familia'
        verbose_name_plural = 'Familias'


class Brand(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre Marca', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'


# class Unit(models.Model):
#     id = models.AutoField(primary_key=True)
#     name = models.CharField('Abreviatura', max_length=5, unique=True)
#     description = models.CharField('Descripción', max_length=100, unique=True)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = 'Unidad'
#         verbose_name_plural = 'Unidades'


class Order(models.Model):
    TYPE_CHOICES = (('T', 'COTIZACIÓN'), ('V', 'VENTA'), ('C', 'COMPRA'))
    COIN_CHOICES = (('1', 'SOLES'), ('2', 'DOLARES'))
    MOTIVE_CHOICES = (('01', 'VENTA'), ('14', 'VENTA SUJETA A CONFIRMACION DEL COMPRADOR'), ('02', 'COMPRA'),
                      ('04', 'TRASLADO ENTRE ESTABLECIMIENTOS DE LA MISMA EMPRESA'),
                      ('18', 'TRASLADO EMISOR ITINERANTE CP'),
                      ('08', 'IMPORTACION'), ('09', 'EXPORTACION'), ('13', 'OTROS'), ('06', 'DEVOLUCION'),)
    DOC_CHOICES = (('0', 'ORDEN'), ('1', 'FACTURA ELECTRÓNICA'), ('2', 'BOLETA ELECTRÓNICA'), ('3', 'NOTA DE CREDITO'),
                   ('4', 'NOTA DE DEBITO'), ('5', 'GUIA DE REMISION'))
    ADD_CHOICES = (('N', 'NINGUNA'), ('G', 'GUIA DE REMISIÓN'))
    MODALITY_TRANSPORT_CHOICES = (('1', 'PUBLICO'), ('2', 'PRIVADO'))
    STATUS_CHOICES = (
        ('P', 'PENDIENTE'), ('R', 'REALIZADA'), ('E', 'EMITIDO'), ('A', 'ANULADA'), ('N', 'NOTA DE CREDITO'),
        ('G', 'GUIA DE REMISION'))
    CONDITION_CHOICES = (('R', 'REALIZADO'), ('PA', 'PENDIENTE ANULACION'), ('A', 'ANULADA'))
    id = models.AutoField(primary_key=True)
    type = models.CharField('TIPO', max_length=1, choices=TYPE_CHOICES, default='T')
    doc = models.CharField('Documento', max_length=1, choices=DOC_CHOICES, default='0')
    add = models.CharField('Adicionales', max_length=1, choices=ADD_CHOICES, default='N')
    number = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    correlative = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    status = models.CharField('ESTADO', max_length=1, choices=STATUS_CHOICES, default='P')
    total = models.DecimalField('TOTAL', max_digits=30, decimal_places=6, default=0)
    total_discount = models.DecimalField('DESCUENTO', max_digits=30, decimal_places=4, default=0)
    coin = models.CharField('TIPO', max_length=1, choices=COIN_CHOICES, default='1')
    change = models.DecimalField('CAMBIO DE MONEDA', max_digits=30, decimal_places=4, default=1)
    create_at = models.DateField(null=True, blank=True)
    update_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True, blank=True)
    person = models.ForeignKey(Person, verbose_name='CLIENTE/PROVEEDOR',
                               on_delete=models.SET_NULL, null=True, blank=True)
    quotation = models.IntegerField(verbose_name='COTIZACION', null=True, blank=True)
    is_igv = models.BooleanField('IGV', default=True)
    date_document = models.DateField(null=True, blank=True)
    invoice_number = models.CharField('Numero Factura', max_length=50, null=True, blank=True)
    invoice_date = models.DateField("Fecha Ingreso", null=True, blank=True)
    license_plate = models.CharField('Placa', max_length=50, null=True, blank=True)
    paid = models.DecimalField('PAGADO', max_digits=30, decimal_places=4, default=0)
    bill_serial = models.CharField(max_length=50, null=True, blank=True, default='-')
    bill_type = models.CharField('TIPO', max_length=2, null=True, blank=True)
    bill_number = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    bill_status = models.CharField('Sunat Status', max_length=5, null=True, blank=True)
    bill_description = models.CharField('Sunat descripcion', max_length=500, null=True, blank=True)
    bill_enlace_pdf = models.CharField('Sunat Enlace Pdf', max_length=500, null=True, blank=True)

templates/finances/order_detail_form.html
{% load operations %}
<style>
    .bg-transparent{
        background-color: #28a745!important;
        border: 1px solid #28a745;
    }
</style>
<div class="row mb-3">

        <label for="credit-note-invoice-number" class="col-sm-2 col-form-label">Nro nota credito</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" id="credit-note-invoice-number-name" value="" maxlength="50">
          <input type="hidden" class="form-control" id="guide_id" value="{{ guide_id }}">
        </div>


        <label for="credit-note-date-document" class="col-sm-2 col-form-label">Fecha Emisión</label>
        <div class="col-sm-4">
          <input type="date" class="form-control" id="credit-note-date-document" value="{{ date|date:'Y-m-d' }}">
        </div>
</div>

<div class="row mb-3">
    <label for="credit-note-invoice-date" class="col-sm-2 col-form-label">Fecha Ingreso</label>
    <div class="col-sm-4">
      <input type="date" class="form-control" id="credit-note-invoice-date" value="{{ date|date:'Y-m-d' }}">
    </div>

    <label for="credit-note-date" class="col-sm-2 col-form-label">Fecha Validez</label>
    <div class="col-sm-4">
      <input type="date" class="form-control" id="credit-note-date" value="{{ date|date:'Y-m-d' }}">
    </div>
</div>


<div class="form-group row">
    <label for="static-purchase-supplier-name" class="col-sm-2 col-form-label">Proveedor</label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control bg-transparent" id="static-purchase-supplier-name" value="{{ order_obj.person.names }}">
    </div>
  </div>

<div class="row mb-3">
    <label for="static-purchase-doc" class="col-sm-2 col-form-label">COMPROBANTE</label>
    <div class="col-sm-4">
      <input type="text" readonly class="form-control bg-transparent" id="static-purchase-doc" value="{{ order_obj.get_doc_display }}">
    </div>

    <div class="col-sm-3">
      <input type="text" readonly class="form-control bg-transparent" id="static-purchase-invoice-related-id" value="{{ order_obj.invoice_number }}">
    </div>

    <div class="col-sm-3">
      <input type="date" readonly class="form-control bg-transparent" id="static-purchase-create-at" value="{{ order_obj.date_document|date:'Y-m-d' }}">
    </div>

  </div>

<div class="table-responsive">
    <table class="table table-sm table-bordered table-striped table-order-detail">
        <thead>
        <tr>
            <td>CODIGO</td>
            <td>PRODUCTO</td>
            <td>MEDIDAS</td>
            <td>UNIDAD</td>
            <td>PRECIO</td>
            <td>CANTIDAD<br>COMPRADA</td>
            <td>CANTIDAD<br>A DEVOLVER</td>
            <td>SUBTOTAL<br>NOTA CREDITO</td>
            <td>SUBTOTAL<br>COMPRA </td>
        </tr>
        </thead>
        <tbody>
        {% for d in detail_dict %}
{#            {% for a in order_obj.order_set.all.last.orderdetail_set.all %}#}
                <tr pk="{{ d.id }}">
                    <td class="align-middle text-center">{{ d.product_code }}</td>
                    <td class="align-middle">{{ d.product_name }}</td>
                    <td class="align-middle" a="{{ d.product_with }}" l="{{ d.product_length }}" h="{{ d.product_height }}">
                        <strong>ANCHO: {{ d.product_with }}<br>LARGO: {{ d.product_length }}<br>ALTO: {{ d.product_height }}</strong>
                    </td>
                    <td class="align-middle">{{ d.unit }}</td>
                    <td class="align-middle">{{ d.price|safe }}</td>
                    <td class="align-middle"><input type="text" class="form-control bg-transparent text-right quantity-purchased" value="{{ d.quantity|safe }}" readonly /></td>
                    <td class="align-middle"><input type="text" class="form-control text-right quantity-returned" readonly detail-id="{{ d.id }}" max-value="{{ d.quantity|safe }}" value="{{ d.quantity_returned|safe }}" /></td>
                    <td class="align-middle"><input type="text" class="form-control bg-transparent text-right new-subtotal" value="{{ d.amount|safe }}" readonly /></td>
                    <td class="align-middle"><input type="text" class="form-control bg-transparent text-right old-subtotal" value="{{ d.amount|safe }}" readonly /></td>
                </tr>
{#            {% endfor %}#}
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td class="small align-bottom" colspan="6">MONEDA: {{ order_obj.get_coin_display }}</td>
            <td>BASE</td>
            <td><input type="text" class="form-control bg-transparent text-right new-base" value="{{ order_obj.order_set.all.last.total|get_sub_total }}"/></td>
            <td><input type="text" class="form-control bg-transparent text-right old-base" value="{{ order_obj.total|safe }}" readonly /></td>
        </tr>

        <tr>
            <td class="small align-bottom" colspan="6">T.C.: {{ order_obj.change|safe }}</td>
            <td>IGV</td>
            <td><input type="text" class="form-control bg-transparent text-right new-igv" value="{{ order_obj.order_set.all.last.total|get_igv }}" readonly /></td>
            <td><input type="text" class="form-control bg-transparent text-right old-igv" value="{{ order_obj.total|safe }}" readonly /></td>
        </tr>

        <tr>
            <td colspan="6"></td>
            <td>TOTAL</td>
            <td><input type="text" class="form-control bg-transparent text-right new-total" value="{{ order_obj.order_set.all.last.total|safe }}" readonly /></td>
            <td><input type="text" class="form-control bg-transparent text-right old-total" value="{{  order_obj.order_set.all.last.get_purchase_total|safe }}" readonly /></td>
        </tr>

        </tfoot>

    </table>
</div>

<script>

</script>

templates/finances/order_supplier_grid.html
<table id="example1" class="table table-bordered table-striped">
    <thead>
    <tr class="text-center">
        <th class="bg-primary-light1">Nº</th>
        <th class="bg-primary-light1">Comprobante</th>
        <th class="bg-primary-light1">Tipo Comprobante</th>
        <th class="bg-primary-light1">Estado</th>
        <th class="bg-primary-light1">Fecha Documento</th>
        <th class="bg-primary-light1">Moneda</th>
        <th class="bg-primary-light1">Cambio</th>
        <th class="bg-primary-light1">Total</th>
        <th class="bg-success-light2">NC</th>
        <th class="bg-success-light2">TOTAL</th>
        <th class="bg-success-light2">EMISION</th>
        <th class="bg-success-light1" colspan="2">ACCIONES</th>
    </tr>
    </thead>
    <tbody id="order_list">
    {% for o in order_set %}
        <tr class="text-center" order="{{ o.id }}">
            <td class="align-middle p-1 bg-primary-light1">{{ o.number }}</td>
            <td class="align-middle p-1 bg-primary-light1">{{ o.invoice_number }}</td>
            <td class="align-middle p-1 bg-primary-light1">{{ o.get_doc_display }}</td>
            <td class="align-middle p-1 bg-primary-light1">{{ o.get_status_display }}</td>
            <td class="align-middle p-1 bg-primary-light1">{{ o.date_document|date:'d-m-Y' }}</td>
            <td class="align-middle p-1 bg-primary-light1">{{ o.get_coin_display|safe }}</td>
            <td class="align-middle p-1 bg-primary-light1">{{ o.change|safe }}</td>
            <td class="text-right align-middle p-1 bg-primary-light1">{{ o.total|safe }}</td>

            <td class="text-right align-middle p-1 bg-success-light2">
                {% if o.order_set.exists and o.order_set.all.last.status == 'N' %}
                    {{ o.order_set.all.last.invoice_number }}{% endif %}</td>
            <td class="text-right align-middle p-1 bg-success-light2">
                {% if o.order_set.exists and o.order_set.all.last.status == 'N' %}
                    {{ o.order_set.all.last.total|safe }}{% endif %}</td>
            <td class="text-right align-middle p-1 bg-success-light2">
                {% if o.order_set.exists and o.order_set.all.last.status == 'N' %}
                    {{ o.order_set.all.last.date_document|date:'d-m-Y' }}{% endif %}</td>

            <td class="align-middle p-1 bg-success-light1">

                {% if o.order_set.exists and o.order_set.all.last.status == 'G' %}
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-sm btn-light w-100"
                                onclick="DownloadGuideReturn({{ o.order_set.all.last.id }})">
                            <i class="icon-arrow-down-circle"></i> Guia
                            {{ o.order_set.all.last.guide_serial }}-{{ o.order_set.all.last.guide_number }}
                        </button>
                        <button type="button" value="{{ o.id }}" data-toggle="modal" data-target="#purchaseModal"
                                class="btn btn-success btn-block btn-sm show-items"><i class="icon-list"></i> Crear Nota
                            Credito
                        </button>
                    </div>
                {% elif o.order_set.exists and o.order_set.all.last.status == 'N' %}
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-sm btn-light w-100"
                                onclick="DownloadGuideReturn({{ o.order_set.all.last.id }})">
                            <i class="icon-arrow-down-circle"></i> Guia
                            {{ o.order_set.all.last.guide_serial }}-{{ o.order_set.all.last.guide_number }}
                        </button>
                        <button type="button" value="{{ o.order_set.all.last.id }}" data-toggle="modal"
                                data-target="#creditNoteModal"
                                class="btn btn-danger btn-sm btn-block show-credit-note-items"><i class="icon-list"></i>
                            Ver Nota Credito
                        </button>
                    </div>
                {% else %}
                    <button type="button" value="{{ o.id }}"
                            class="btn btn-primary btn-block btn-sm create-guide"><i class="icon-list"></i> Crear
                        Guia
                    </button>
                {% endif %}

                {#                        {% if o.order_set.exists and o.order_set.all.last.status == 'N' %}#}
                {#                            <button type="button" value="{{ o.order_set.all.last.id }}" data-toggle="modal"#}
                {#                                    data-target="#creditNoteModal"#}
                {#                                    class="btn btn-danger btn-block show-credit-note-items"><i class="icon-list"></i>#}
                {#                                Ver Nota Credito#}
                {#                            </button>#}
                {#                            {% if o.order_set.all.last.add == 'G' %}#}
                {#                                <button type="button" class="btn btn-light w-100"#}
                {#                                        onclick="DownloadGuideReturn({{ o.order_set.all.last.id }})">#}
                {#                                    <i class="icon-arrow-down-circle"></i> Ver Guia#}
                {#                                    {{ o.order_set.all.last.guide_serial }}-{{ o.order_set.all.last.guide_number }}#}
                {#                                </button>#}
                {#                            {% else %}#}
                {#                                <button type="button" value="{{ o.order_set.all.last.id }}"#}
                {#                                        class="btn btn-primary btn-block create-guide"><i class="icon-list"></i> Crear#}
                {#                                    Guia#}
                {#                                </button>#}
                {#                            {% endif %}#}
                {#                        {% else %}#}
                {#                            <button type="button" value="{{ o.id }}" data-toggle="modal" data-target="#purchaseModal"#}
                {#                                    class="btn btn-success btn-block show-items"><i class="icon-list"></i> Crear Nota#}
                {#                                Credito#}
                {#                            </button>#}
                {#                            <button type="button" value="{{ o.id }}"#}
                {#                                    class="btn btn-primary btn-block create-guide"><i class="icon-list"></i> Crear#}
                {#                                Guia#}
                {#                            </button>#}
                {#                        {% endif %}#}
            </td>
            <td class="align-middle p-1 bg-success-light1">
                <button type="button" value="{{ o.id }}" data-toggle="modal" data-target="#showPurchaseModal"
                        class="btn btn-secondary btn-block show-purchase-items"><i class="icon-list"></i>
                    Ver Compra
                </button>
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="12"><p class="text-warning">No existen resultados</p></td>
        </tr>
    {% endfor %}
    </tbody>
</table>